export const NEW_LINE = "\n";
export const EMPTY_STRING = "";
export const NO_SPACE = "";
export const UPPERCASE_LETTERS = [ "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" ];
export const LOWERCASE_LETTERS = [ "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z" ];
export const NUMERIC_LETTERS = [ "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" ];
export const SYMBOL_LETTERS = [ "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "[", "]", "=" ];
export const MIN_OUTPUT_ITEMS = 1;
export const MAX_OUTPUT_ITEMS = 100;
export const OUTPUT_ITEMS = 25;
