name: ci
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Setup build env
        run: |
          npm install -g yarn
          yarn install
      - name: Check code formatting
        run: yarn lint:check
      - name: Build
        run: yarn build
      - name: publish docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          cname: boring-devtools.com
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist
